import assert from 'node:assert/strict';
import {applyCommand,eligibility,parseSource} from '../lib/commands';
import {seedProducts,selectedModules,packageValid,Workspace} from '../lib/workflow';
let w:Workspace={products:seedProducts(),revision:0};
assert.deepEqual(parseSource('只有一段没有字段的文字').map(f=>[f.name,f.value]).sort(),[['商品名称',''],['类目','']].sort());
assert.equal(parseSource('品名：旅行背包\n分类：箱包').find(f=>f.name==='商品名称')?.value,'旅行背包');
assert.equal(parseSource('商品名称：A\n商品名称：B\n类目：箱包').find(f=>f.name==='商品名称')?.value,'');
assert.throws(()=>applyCommand(w,{action:'generate',id:'p-3'}));
let p=w.products.find(p=>p.id==='p-3')!;
w=applyCommand(w,{action:'fields',id:p.id,fields:p.fields.map(f=>({...f,confirmed:true}))}).workspace;
w=applyCommand(w,{action:'generate',id:p.id}).workspace;p=w.products.find(p=>p.id==='p-3')!;
assert.equal(p.versions.length,3);assert.ok(packageValid(p));assert.equal(p.versions[0].fieldsSnapshot?.length,p.fields.length);
const chosen=p.versions[1].id;w=applyCommand(w,{action:'choose',id:p.id,module:'商品标题',versionId:chosen}).workspace;p=w.products.find(p=>p.id==='p-3')!;
assert.equal(p.selection['商品标题'],chosen);assert.notEqual(p.selection['核心卖点'],chosen);
assert.throws(()=>applyCommand(w,{action:'export',ids:[p.id]}));
assert.throws(()=>applyCommand(w,{action:'publish',id:p.id}));
w=applyCommand(w,{action:'submit',id:p.id}).workspace;w=applyCommand(w,{action:'approve',id:p.id}).workspace;
const out=applyCommand(w,{action:'export',ids:[p.id]});assert.equal((out.result.exports as unknown[]).length,1);w=out.workspace;
assert.equal(w.products.find(v=>v.id===p.id)?.stage,'ready');
w=applyCommand(w,{action:'publish',id:p.id}).workspace;
assert.equal(w.products.find(v=>v.id===p.id)?.stage,'published');
const live=JSON.stringify(w.products.find(v=>v.id===p.id)?.publications);
w=applyCommand(w,{action:'publish',id:p.id}).workspace;assert.equal(JSON.stringify(w.products.find(v=>v.id===p.id)?.publications),live);
w=applyCommand(w,{action:'export',ids:[p.id]}).workspace;assert.equal(w.products.find(v=>v.id===p.id)?.stage,'published');
p=w.products.find(p=>p.id==='p-3')!;const savedVersion=p.versions[0].id;
w=applyCommand(w,{action:'fields',id:p.id,fields:p.fields.map(f=>({...f,value:f.name==='规格'?'2L 水箱':f.value}))}).workspace;p=w.products.find(p=>p.id==='p-3')!;
assert.equal(JSON.stringify(p.publications),live);assert.throws(()=>applyCommand(w,{action:'publish',id:p.id}));
assert.equal(p.fieldRevision,2);assert.equal(p.approvedRevision,null);assert.equal(packageValid(p),false);assert.equal(p.versions.length,3);assert.throws(()=>applyCommand(w,{action:'choose',id:p.id,module:'商品标题',versionId:savedVersion}));assert.throws(()=>applyCommand(w,{action:'export',ids:[p.id]}));
assert.equal(p.versions[0].fieldsSnapshot?.find(f=>f.name==='规格')?.value,'1.5L 水箱');
assert.ok(eligibility(w.products.find(p=>p.id==='p-2')!,'submit'));
w=applyCommand(w,{action:'deliver',id:'p-2',url:'https://example.com/design'}).workspace;
assert.equal(eligibility(w.products.find(p=>p.id==='p-2')!,'submit'),null);
const batch=applyCommand(w,{action:'batch',operation:'generate',ids:['p-1','p-6','p-6']});
assert.deepEqual((batch.result.outcomes as {status:string}[]).map(o=>o.status),['skipped','done']);
w=batch.workspace;assert.equal(w.products.find(p=>p.id==='p-1')!.stage,'review');
p=w.products.find(p=>p.id==='p-4')!;w=applyCommand(w,{action:'edit',id:p.id,modules:{...selectedModules(p),'商品标题':'人工确认的新标题'}}).workspace;
assert.equal(w.products.find(item=>item.id==='p-4')?.approvedRevision,null);assert.throws(()=>applyCommand(w,{action:'export',ids:['p-4']}));
console.log('Passed: import validation, field gate, module single selection, review/publish/export gates, publication immutability and idempotence, source snapshots, invalidation, design gate, mixed-state batch and edit invalidation.');

let minimal=applyCommand(w,{action:'create',source:'品名：新商品\n分类：箱包',owner:'陈思思'});let minimalId=minimal.result.id as string;w=minimal.workspace;let minP=w.products.find(p=>p.id===minimalId)!;w=applyCommand(w,{action:'fields',id:minimalId,fields:minP.fields.map(f=>({...f,confirmed:true}))}).workspace;w=applyCommand(w,{action:'generate',id:minimalId}).workspace;minP=w.products.find(p=>p.id===minimalId)!;for(const version of minP.versions){const chosen=applyCommand(w,{action:'chooseVersion',id:minimalId,versionId:version.id});assert.equal(eligibility(chosen.workspace.products.find(p=>p.id===minimalId)!,'submit'),null)}
console.log('Passed: minimum facts generate usable versions.');
