export type Stage='confirm'|'generate'|'review'|'design'|'ready'|'exported'|'published'|'failed';
export type Field={name:string;value:string;source:string;confirmed:boolean};
export type ContentVersion={id:string;label:string;fieldRevision:number;fieldsSnapshot?:Field[];engine?:string;elapsedMs?:number;modules:Record<string,string>;at:string};
export type Publication={id:string;at:string;packageRevision:number;fieldRevision:number;name:string;category:string;sku:string;image:string;modules:Record<string,string>;fields:Field[]};
export type Product={id:string;name:string;sku:string;category:string;owner:string;image:string;stage:Stage;fields:Field[];fieldRevision:number;versions:ContentVersion[];selection:Record<string,string>;packageRevision:number;approvedRevision:number|null;history:{at:string;text:string}[];source:string;updated:string;designRequired:boolean;designDelivered:boolean;due:string;publications?:Publication[];lastExportedAt?:string};
export type Workspace={products:Product[];revision:number};
export const stageInfo:Record<Stage,{label:string;color:string;action:string}>={confirm:{label:'字段待确认',color:'blue',action:'核对资料'},generate:{label:'待生成内容',color:'purple',action:'生成内容'},review:{label:'内容待审核',color:'purple',action:'审核内容'},design:{label:'设计进行中',color:'orange',action:'查看设计'},ready:{label:'待发布商品',color:'orange',action:'发布商品'},exported:{label:'待发布商品',color:'orange',action:'发布商品'},published:{label:'已发布',color:'green',action:'查看商品'},failed:{label:'需要处理',color:'red',action:'查看原因'}};
export const moduleNames=['商品标题','核心卖点','商品描述','SEO 关键词','设计需求'];
export const sourceBackpack='商品名称：城市通勤双肩包\n品牌：UrbanCarry\n类目：箱包配饰\n容量：22L\n尺寸：45 × 30 × 16 cm\n材质：高密度防泼水牛津布\n颜色：黑色 / 深灰色\n适用场景：日常通勤、短途出行\n价格：¥199\n适配：15.6 英寸笔记本电脑';
export function makeVersions(p:Product):ContentVersion[]{const get=(n:string)=>p.fields.find(f=>f.name===n)?.value||'';const facts=p.fields.filter(f=>f.confirmed&&f.value&&f.name!=='商品名称').map(f=>`${f.name}：${f.value}`);return ['标准版','场景版','搜索版'].map((label,i)=>({id:crypto.randomUUID(),label,fieldRevision:p.fieldRevision,fieldsSnapshot:structuredClone(p.fields),at:new Date().toISOString(),modules:{'商品标题':i===0?`${get('品牌')} ${p.name}`.trim():i===1?`${p.name} · ${get('适用场景')||p.category}`:`${p.name} ${get('容量')||get('材质')||p.category}`,'核心卖点':(i===1&&facts.length>1?facts.slice(1,5):facts.slice(0,4)).join('\n'),'商品描述':`${p.name}。${facts.join('；')}。`,'SEO 关键词':[p.name,p.category,get('品牌'),get('适用场景')].filter(Boolean).join(' / '),'设计需求':`围绕「${p.name}」制作商品主图与详情图。\n突出已确认信息：${facts.slice(0,4).join('；')}。\n使用商品实拍素材，设计交付后进入内容审核。`}}))}
export function selectedModules(p:Product):Record<string,string>{return Object.fromEntries(moduleNames.map(n=>[n,p.versions.find(v=>v.id===p.selection[n])?.modules[n]||'']))}
export function packageValid(p:Product){return moduleNames.every(n=>{const v=p.versions.find(v=>v.id===p.selection[n]);return v?.fieldRevision===p.fieldRevision&&!!v.modules[n]?.trim()})}
export function seedProducts():Product[]{const specs:[string,string,string,string,Stage,string][]=[['玻尿酸保湿精华套装','美妆护肤','skincare','陈思思','review','今天 17:00'],['城市通勤双肩包','箱包配饰','backpack','张夏明','design','今天 18:00'],['全自动意式咖啡机','家用电器','coffee','梁欣','confirm','今天 17:30'],['节日限定礼盒套装','生活方式','gift','董莹莹','ready','明天 12:00'],['轻量跑步运动鞋','服饰鞋靴','shoes','陈思思','failed','今天 18:30'],['智能保温杯 500mL','生活方式','bottle','梁欣','generate','明天 10:00'],['氨基酸净透面膜 10片','美妆护肤','mask','张夏明','review','明天 14:00'],['轻旅双肩包 · 雾灰','箱包配饰','backpack','陈思思','exported','已完成']];return specs.map(([name,category,image,owner,stage,due],i)=>{const source=i===1?sourceBackpack:`商品名称：${name}\n品牌：${['Hydralab','UrbanCarry','BrewLab','日常集','Pace','Warmly','Hydralab','UrbanCarry'][i]}\n类目：${category}\n规格：${['精华 30mL × 3','22L','1.5L 水箱','礼盒装','36–44 码','500mL','10片装','22L'][i]}`;const fields=source.split('\n').filter(l=>l.includes('：')).map(l=>{const [n,...v]=l.split('：');return {name:n,value:v.join('：'),source:l,confirmed:stage!=='confirm'}});const p:Product={id:`p-${i+1}`,name,category,sku:`CF-${String(i+1).padStart(4,'0')}`,owner,image,stage,fields,fieldRevision:1,versions:[],selection:{},packageRevision:1,approvedRevision:null,history:[{at:'2026-09-10T06:30:00.000Z',text:'已导入示例商品资料'}],source,updated:'2026-09-10T06:30:00.000Z',designRequired:stage==='design',designDelivered:false,due};if(['review','design','ready','exported'].includes(stage)){p.versions=makeVersions(p);p.selection=Object.fromEntries(moduleNames.map((n,j)=>[n,p.versions[j===1?1:0].id]));}if(['ready','exported'].includes(stage))p.approvedRevision=p.packageRevision;return p})}
